# Generated by Django 2.0.7 on 2018-07-31 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeekCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invation_code', models.CharField(max_length=8)),
                ('is_available', models.BooleanField(default=True)),
                ('code_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
