# Generated by Django 2.0.7 on 2018-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekuser', '0002_geekcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geekcode',
            name='code_user',
        ),
        migrations.AlterField(
            model_name='geekuser',
            name='sub_invation_code',
            field=models.TextField(),
        ),
    ]
